<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BaconLiquibase\Controller\AggregateController' => __DIR__ . '/src/BaconLiquibase/Controller/AggregateController.php',
    'BaconLiquibase\Module'                         => __DIR__ . '/Module.php',
);